### ISSUE TITLE
list of improvements

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/infrastructure-playbook#38]
* there is /var/log/supervisor/ and /var/log/supervisord/, the latter is not used
* galaxy user does not have write permisions to /var/log/supervisor/

**Comment by erasche** [comment]
Per out of band discussion, nothing should be written to either of these locations, they are not relevant for the operation of Galaxy.

At some point we will likely switch to systemd instead of supervisord solving this completely, now that @ooobik helpfully figured out some of the issues remaining with that.

**Comment by ooobik** [comment]
To be honest, I still am figuring out some of the bugs with systemd. I'm currently not sure wether they are tied to the .venv location move or systemd.

**Comment by ooobik** [comment]
Further testing reveals this was a user reporting an older error that I fixed in both docs and our galaxy yesterday. Systemd so far seems to be doing better than supervisor - being able to see command logs (not the one specified with --log but stdout) is immensely useful, especially for newer admins.

Only question with systemd is envvar variable expansion, which service files themselves don't do. Either have to expand the path manually (done in docs) or create a service.d directory with extra params.

**Comment by erasche** [comment]
Awesome :) For envvar expansion, ok, interesting. From my side, perfectly fine to expand manually
